name: CI

# triggers that whenever you push or pull_request will happen
on:
  push:
  pull_request:
  # you can use a pre-commit hook

jobs:
  run-tests:
    strategy:
      fail-fast: false # no cascade failing, we want to see where it failed
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12-dev"
          - "pypy-3.7"
          - "pypy-3.8"
          - "pypy-3.9"

    name: Test
    runs-on: ${{ matrix.os }} # tells Github to use the matrix os defined above

    steps:
      - name: Checkout code # brings code into Github runner
        uses: actions/checkout@v3 # checkout actions and version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install pytest
          python -m pip install hypothesis

      - name: Run tests
        run: pytest -v
